const STORAGE_KEY='prompt-assistant-v1';
document.documentElement.classList.toggle('electron',navigator.userAgent.includes('Electron'));
const translations={
zh:{tagline:'你的常用表达，一键即用',quick:'快速唤起',newScene:'新建场景',history:'历史指令',tip:'提示',shortcutTip:'按 ⌘ K 搜索，↑↓ 选择，Enter 复制。',newPrompt:'新建 Prompt',all:'全部',favorites:'收藏',copyHint:'点击卡片复制完整 Prompt',noResults:'没有找到 Prompt',noResultsHelp:'换个关键词，或者新建一个属于你的 Prompt。',historyHelp:'删除的内容会保留在这里，直到你手动清空。',clearAll:'一键清空',title:'标题',scene:'所属场景',promptContent:'Prompt 内容',tags:'标签',commaSeparated:'用逗号分隔',delete:'删除',cancel:'取消',savePrompt:'保存 Prompt',sceneName:'场景名称',chooseIcon:'选择图标',createScene:'创建场景',light:'白昼模式',dark:'黑夜模式',search:'搜索标题、内容或标签...',allPrompts:'全部 Prompts',allSubtitle:'找到你需要的表达，然后直接复制使用。',sceneSubtitle:n=>`管理和使用你的「${n}」常用表达。`,historySubtitle:'查看已经删除的场景和 Prompt。',count:n=>`${n} 个 Prompt`,clickCopy:'点击复制 ↗',chars:n=>`${n} 字`,historyEmpty:'历史记录是空的',deletedScene:n=>`已删除场景 · 包含 ${n} 个 Prompt`,deletedPrompt:n=>`已删除 Prompt · ${n||'未知场景'}`,editPrompt:'编辑 Prompt',newPromptTitle:'新建 Prompt'},
en:{tagline:'Your go-to prompts, one click away',quick:'Quick open',newScene:'New scene',history:'History',tip:'TIP',shortcutTip:'⌘ K to search, ↑↓ to select, Enter to copy.',newPrompt:'New Prompt',all:'All',favorites:'Favorites',copyHint:'Click a card to copy the full prompt',noResults:'No prompts found',noResultsHelp:'Try another keyword or create a new prompt.',historyHelp:'Deleted items stay here until you clear them.',clearAll:'Clear all',title:'Title',scene:'Scene',promptContent:'Prompt content',tags:'Tags',commaSeparated:'comma-separated',delete:'Delete',cancel:'Cancel',savePrompt:'Save Prompt',sceneName:'Scene name',chooseIcon:'Choose an icon',createScene:'Create scene',light:'Light mode',dark:'Dark mode',search:'Search titles, content, or tags...',allPrompts:'All Prompts',allSubtitle:'Find the right words and copy them in one click.',sceneSubtitle:n=>`Manage and use your prompts for “${n}”.`,historySubtitle:'View deleted scenes and prompts.',count:n=>`${n} Prompt${n===1?'':'s'}`,clickCopy:'Click to copy ↗',chars:n=>`${n} chars`,historyEmpty:'History is empty',deletedScene:n=>`Deleted scene · ${n} Prompt${n===1?'':'s'}`,deletedPrompt:n=>`Deleted Prompt · ${n||'Unknown scene'}`,editPrompt:'Edit Prompt',newPromptTitle:'New Prompt'},
fr:{tagline:'Vos prompts favoris, en un clic',quick:'Ouverture rapide',newScene:'Nouvelle catégorie',history:'Historique',tip:'ASTUCE',shortcutTip:'⌘ K pour chercher, ↑↓ pour choisir, Entrée pour copier.',newPrompt:'Nouveau Prompt',all:'Tous',favorites:'Favoris',copyHint:'Cliquez sur une carte pour copier le prompt',noResults:'Aucun prompt trouvé',noResultsHelp:'Essayez un autre mot-clé ou créez un prompt.',historyHelp:'Les éléments supprimés restent ici jusqu’au vidage.',clearAll:'Tout effacer',title:'Titre',scene:'Catégorie',promptContent:'Contenu du prompt',tags:'Tags',commaSeparated:'séparés par des virgules',delete:'Supprimer',cancel:'Annuler',savePrompt:'Enregistrer',sceneName:'Nom de la catégorie',chooseIcon:'Choisir une icône',createScene:'Créer',light:'Mode clair',dark:'Mode sombre',search:'Rechercher dans les titres, contenus ou tags...',allPrompts:'Tous les prompts',allSubtitle:'Trouvez la bonne formulation et copiez-la en un clic.',sceneSubtitle:n=>`Gérez et utilisez vos prompts « ${n} ».`,historySubtitle:'Consultez les catégories et prompts supprimés.',count:n=>`${n} Prompt${n===1?'':'s'}`,clickCopy:'Cliquer pour copier ↗',chars:n=>`${n} car.`,historyEmpty:'L’historique est vide',deletedScene:n=>`Catégorie supprimée · ${n} Prompt${n===1?'':'s'}`,deletedPrompt:n=>`Prompt supprimé · ${n||'Catégorie inconnue'}`,editPrompt:'Modifier le Prompt',newPromptTitle:'Nouveau Prompt'}};
let language=localStorage.getItem('prompt-mate-language')||'zh',theme=localStorage.getItem('prompt-mate-theme')||'light';
const tr=(key,...args)=>{const value=translations[language][key]??translations.zh[key]??key;return typeof value==='function'?value(...args):value};
const starter={scenes:[{id:'all',name:'全部 Prompts',icon:'⌂',fixed:true},{id:'french',name:'法语学习',icon:'🇫🇷'},{id:'english',name:'英语学习',icon:'🇬🇧'},{id:'fitness',name:'健身计划',icon:'🏃'},{id:'visual',name:'图像与视频',icon:'✦'}],prompts:[
{id:'p1',sceneId:'french',title:'纠正我的法语表达',content:'你是一位耐心的法语老师。请纠正下面这段法语，先给出自然、地道的版本，再逐条解释语法和用词问题。最后提供 2 个同义表达，并标注正式/口语语境。\n\n我的原文：{粘贴内容}',tags:['纠错','表达'],favorite:true},
{id:'p2',sceneId:'french',title:'生成情境对话练习',content:'请围绕「{场景}」创作一段 B1-B2 难度的法语对话。对话要自然、贴近日常，每句话后附中文解释。结尾列出 8 个值得记忆的表达，并用它们生成填空练习。',tags:['口语','对话'],favorite:false},
{id:'p3',sceneId:'english',title:'让英文更自然简洁',content:'Rewrite the following text in clear, natural English. Keep my original meaning and tone, remove unnecessary words, and avoid corporate jargon. Then briefly explain the three most important changes.\n\nText: {paste here}',tags:['写作','润色'],favorite:true},
{id:'p4',sceneId:'english',title:'会议前口语准备',content:'I have a meeting about {topic}. Act as my speaking coach. Give me 10 useful phrases, then role-play a realistic discussion with me one question at a time. Correct only mistakes that affect clarity.',tags:['口语','会议'],favorite:false},
{id:'p5',sceneId:'fitness',title:'制定一周训练计划',content:'你是一位注重长期健康的健身教练。根据我的目标「{目标}」、每周可训练 {次数} 次、器械条件「{条件}」，制定一周训练计划。包含热身、动作、组数、次数、休息和渐进规则，并指出需要注意的风险。',tags:['训练','计划'],favorite:false},
{id:'p6',sceneId:'visual',title:'把想法变成图像 Prompt',content:'将我的想法扩写为专业的图像生成 Prompt。请依次明确：主体、环境、构图、镜头、光线、色彩、材质、情绪和画面比例。输出一个中文版本和一个精炼英文版本，不要擅自添加文字或水印。\n\n想法：{描述你的画面}',tags:['图像','创作'],favorite:true}
]};
let data=loadData(),activeScene='all',activeFilter='all',keyboardIndex=-1,selectedEmoji='✦';
const $=s=>document.querySelector(s),sceneList=$('#sceneList'),grid=$('#promptGrid'),search=$('#searchInput');
function loadData(){try{const stored=JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(starter);stored.trash=stored.trash||[];stored.prompts.forEach(p=>p.copyCount=Number(p.copyCount)||0);return stored}catch{const fresh=structuredClone(starter);fresh.trash=[];fresh.prompts.forEach(p=>p.copyCount=0);return fresh}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function applyPreferences(){document.documentElement.lang=language==='zh'?'zh-CN':language;document.documentElement.dataset.theme=theme;$('#languageSelect').value=language;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));search.placeholder=tr('search');$('#themeIcon').textContent=theme==='dark'?'☀':'☾';$('#themeLabel').textContent=tr(theme==='dark'?'light':'dark')}
function sceneFor(id){return data.scenes.find(s=>s.id===id)}
function visiblePrompts(){const q=search.value.trim().toLowerCase(),list=data.prompts.filter(p=>(activeScene==='all'||p.sceneId===activeScene)&&(activeFilter!=='favorite'||p.favorite)&&(!q||[p.title,p.content,...p.tags].join(' ').toLowerCase().includes(q)));return activeScene==='all'?list.sort((a,b)=>(b.copyCount||0)-(a.copyCount||0)):list}
function renderScenes(){sceneList.innerHTML=data.scenes.map(s=>`<button class="scene-item ${s.id===activeScene?'active':''}" data-scene="${s.id}"><span class="scene-icon">${s.icon}</span><span>${escapeHtml(s.id==='all'?tr('allPrompts'):s.name)}</span><span class="count">${s.id==='all'?data.prompts.length:data.prompts.filter(p=>p.sceneId===s.id).length}</span></button>`).join('');$('#historyCount').textContent=data.trash.length;$('#openHistory').classList.toggle('active',activeScene==='history');document.querySelectorAll('.scene-item').forEach(b=>b.onclick=()=>{activeScene=b.dataset.scene;search.value='';render();$('#sidebar').classList.remove('open')})}
function render(){renderScenes();const isHistory=activeScene==='history';$('#historyView').hidden=!isHistory;$('.search-row').hidden=isHistory;$('.result-meta').hidden=isHistory;$('#addPrompt').hidden=isHistory;$('#sceneEyebrow').textContent=isHistory?'RECENTLY DELETED':'PROMPT LIBRARY';if(isHistory){$('#sceneTitle').textContent=tr('history');$('#sceneSubtitle').textContent=tr('historySubtitle');$('#renameScene').hidden=true;$('#deleteScene').hidden=true;$('#sceneTitle').classList.remove('editable');grid.hidden=true;$('#emptyState').hidden=true;renderHistory();return}const scene=sceneFor(activeScene);if(!scene){activeScene='all';return render()}$('#sceneTitle').textContent=activeScene==='all'?tr('allPrompts'):scene.name;$('#sceneSubtitle').textContent=activeScene==='all'?tr('allSubtitle'):tr('sceneSubtitle',scene.name);const canEdit=!scene.fixed;$('#renameScene').hidden=!canEdit;$('#deleteScene').hidden=!canEdit;$('#sceneTitle').classList.toggle('editable',canEdit);const list=visiblePrompts();$('#resultCount').textContent=tr('count',list.length);grid.innerHTML=list.map((p,i)=>card(p,i)).join('');grid.hidden=!list.length;$('#emptyState').hidden=!!list.length;keyboardIndex=-1;bindCards()}
function renderHistory(){const items=[...data.trash].reverse();$('#historyList').innerHTML=items.length?items.map(item=>{const isScene=item.type==='scene',count=isScene?(item.prompts?.length||0):0;return `<article class="history-item"><span class="history-type">${isScene?(item.scene.icon||'▣'):'⌁'}</span><div><h3>${escapeHtml(isScene?item.scene.name:item.prompt.title)}</h3><p>${isScene?tr('deletedScene',count):tr('deletedPrompt',escapeHtml(item.sceneName||''))}</p></div><time class="history-date">${formatDate(item.deletedAt)}</time></article>`}).join(''):`<div class="history-empty">${tr('historyEmpty')}</div>`}
function formatDate(value){return new Intl.DateTimeFormat(language==='zh'?'zh-CN':language,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
function card(p,i){const s=sceneFor(p.sceneId);return `<article class="prompt-card" data-id="${p.id}" data-index="${i}" tabindex="0"><div class="card-top"><span class="card-scene">${s.icon} ${escapeHtml(s.name)}</span><div class="card-actions"><button class="favorite ${p.favorite?'active':''}" title="${tr('favorites')}">${p.favorite?'♥':'♡'}</button><button class="edit" title="${tr('editPrompt')}">✎</button></div></div><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.content)}</p><div class="tags">${p.tags.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')}</div><div class="copy-line"><span>${tr('chars',p.content.length)}</span><span class="usage-count">${usageLabel(p.copyCount||0)}</span><strong>${tr('clickCopy')}</strong></div></article>`}
function bindCards(){document.querySelectorAll('.prompt-card').forEach(c=>{c.onclick=async e=>{const p=data.prompts.find(x=>x.id===c.dataset.id);if(e.target.closest('.edit'))return openPrompt(p);if(e.target.closest('.favorite')){p.favorite=!p.favorite;save();render();return}await copyPrompt(p)};c.onkeydown=e=>{if(e.key==='Enter')c.click()}})}
async function copyPrompt(p){try{await navigator.clipboard.writeText(p.content)}catch{const t=document.createElement('textarea');t.value=p.content;document.body.append(t);t.select();document.execCommand('copy');t.remove()}p.copyCount=(p.copyCount||0)+1;save();showToast(`已复制「${p.title}」`,'现在可以粘贴到任何地方');render()}
function usageLabel(count){if(language==='en')return `Copied ${count}×`;if(language==='fr')return `Copié ${count}×`;return `已复制 ${count} 次`}
let toastTimer;function showToast(title,subtitle='更改已保存在本机'){$('#toast strong').textContent=title;$('#toast small').textContent=subtitle;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function fillSceneSelect(){const select=$('#promptScene');select.innerHTML=data.scenes.filter(s=>!s.fixed).map(s=>`<option value="${s.id}">${s.icon} ${escapeHtml(s.name)}</option>`).join('')}
function openPrompt(p){fillSceneSelect();$('#promptForm').reset();$('#promptId').value=p?.id||'';$('#dialogTitle').textContent=tr(p?'editPrompt':'newPromptTitle');$('#deletePrompt').hidden=!p;if(p){$('#promptTitle').value=p.title;$('#promptScene').value=p.sceneId;$('#promptContent').value=p.content;$('#promptTags').value=p.tags.join(', ')}else if(activeScene!=='all')$('#promptScene').value=activeScene;$('#promptDialog').showModal();setTimeout(()=>$('#promptTitle').focus(),50)}
$('#promptForm').onsubmit=e=>{e.preventDefault();const id=$('#promptId').value,existing=data.prompts.find(p=>p.id===id);const item={id:id||`p${Date.now()}`,title:$('#promptTitle').value.trim(),sceneId:$('#promptScene').value,content:$('#promptContent').value.trim(),tags:$('#promptTags').value.split(/[,，]/).map(x=>x.trim()).filter(Boolean),favorite:existing?.favorite||false,copyCount:existing?.copyCount||0};if(id)data.prompts[data.prompts.findIndex(p=>p.id===id)]=item;else data.prompts.unshift(item);save();$('#promptDialog').close();render();showToast(id?'修改已保存':'Prompt 已创建')};
$('#deletePrompt').onclick=()=>{const id=$('#promptId').value;if(confirm('确定删除这个 Prompt 吗？删除后可以在「历史指令」中查看。')){const prompt=data.prompts.find(p=>p.id===id);data.trash.push({type:'prompt',prompt:structuredClone(prompt),sceneName:sceneFor(prompt.sceneId)?.name,deletedAt:new Date().toISOString()});data.prompts=data.prompts.filter(p=>p.id!==id);save();$('#promptDialog').close();render();showToast('Prompt 已移至历史指令')}};
const emojis=['✦','💬','📚','💼','🎨','✈️','🧠','🍳','🎯','💡','🎵','📝','🧘','💻','📷','🌱'];
function renderEmojis(){$('#emojiPicker').innerHTML=emojis.map(e=>`<button type="button" class="emoji-choice ${e===selectedEmoji?'selected':''}" data-emoji="${e}" aria-pressed="${e===selectedEmoji}">${e}${e===selectedEmoji?'<span class="emoji-check">✓</span>':''}</button>`).join('')}renderEmojis();
$('#emojiPicker').onclick=e=>{const button=e.target.closest('.emoji-choice');if(!button)return;e.preventDefault();e.stopPropagation();selectedEmoji=button.dataset.emoji;renderEmojis()};
$('#sceneForm').onsubmit=e=>{e.preventDefault();const name=$('#sceneName').value.trim();const id=`s${Date.now()}`;data.scenes.push({id,name,icon:selectedEmoji});save();activeScene=id;$('#sceneDialog').close();$('#sceneForm').reset();render()};
$('#addScene').onclick=()=>$('#sceneDialog').showModal();['#addPrompt','#emptyAdd'].forEach(s=>$(s).onclick=()=>openPrompt());
document.querySelectorAll('[data-close-dialog]').forEach(button=>button.onclick=()=>{const dialog=$(`#${button.dataset.closeDialog}`);dialog.close();dialog.querySelector('form')?.reset()});
function renameActiveScene(){const scene=sceneFor(activeScene);if(!scene||scene.fixed)return;const title=$('#sceneTitle'),oldName=scene.name,input=document.createElement('input');input.id='sceneTitle';input.className='inline-title-input';input.value=oldName;input.maxLength=20;title.replaceWith(input);input.focus();input.select();let done=false;const finish=commit=>{if(done)return;done=true;const value=input.value.trim();if(commit&&value)scene.name=value;const replacement=document.createElement('h1');replacement.id='sceneTitle';replacement.title='点击修改场景名称';replacement.onclick=renameActiveScene;input.replaceWith(replacement);save();render()};input.onblur=()=>finish(true);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();finish(true)}if(e.key==='Escape'){e.preventDefault();finish(false)}}}
$('#sceneTitle').onclick=renameActiveScene;$('#renameScene').onclick=renameActiveScene;
$('#deleteScene').onclick=()=>{const scene=sceneFor(activeScene);if(!scene||scene.fixed)return;const prompts=data.prompts.filter(p=>p.sceneId===scene.id);if(confirm(`确定删除场景「${scene.name}」吗？\n其中 ${prompts.length} 个 Prompt 也会移到「历史指令」。`)){data.trash.push({type:'scene',scene:structuredClone(scene),prompts:structuredClone(prompts),deletedAt:new Date().toISOString()});data.prompts=data.prompts.filter(p=>p.sceneId!==scene.id);data.scenes=data.scenes.filter(s=>s.id!==scene.id);activeScene='all';save();render();showToast('场景已移至历史指令')}};
$('#openHistory').onclick=()=>{activeScene='history';search.value='';render();$('#sidebar').classList.remove('open')};
$('#clearHistory').onclick=()=>{if(!data.trash.length)return;if(confirm('确定永久清空所有历史指令吗？此操作无法撤销。')){data.trash=[];save();render();showToast('历史指令已清空')}};
search.oninput=render;document.querySelectorAll('.filter-button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render()});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.focus();search.select()}if(document.activeElement===search&&['ArrowDown','ArrowUp','Enter'].includes(e.key)){const cards=[...document.querySelectorAll('.prompt-card')];if(!cards.length)return;e.preventDefault();if(e.key==='Enter'&&keyboardIndex>=0)return cards[keyboardIndex].click();keyboardIndex=e.key==='ArrowDown'?Math.min(keyboardIndex+1,cards.length-1):Math.max(keyboardIndex-1,0);cards.forEach((c,i)=>c.classList.toggle('keyboard-active',i===keyboardIndex));cards[keyboardIndex].scrollIntoView({block:'nearest'})}if(e.key==='Escape'&&document.activeElement===search){search.value='';search.blur();render()}});
$('#focusSearch').onclick=()=>search.focus();$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');
$('#languageSelect').onchange=e=>{language=e.target.value;localStorage.setItem('prompt-mate-language',language);applyPreferences();render()};
$('#themeToggle').onclick=()=>{theme=theme==='dark'?'light':'dark';localStorage.setItem('prompt-mate-theme',theme);applyPreferences()};
function escapeHtml(v=''){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
applyPreferences();render();
